---
- name: Update Vim
  hosts: servers
  become: true
  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    - name: Update Vim to the latest version
      package:
        name: vim
        state: latest

