---
- name: Install NGINX with HTTPS and reverse proxy
  hosts: servers
  become: true
  tasks:
  - name: Update apt package cache
    apt:
      update_cache: yes

  - name: Install NGINX
    apt:
      name: nginx
      state: latest

  - name: Ensure Python3 is installed
    apt:
      name: python3 
      state: latest

  - name: Install Certbot
    apt:
      name: certbot
      state: latest

  - name: Install Certbot Nginix Plugin
    apt:
      name: python3-certbot-nginx
      state: latest

  - name: Obtain Let's Encrypt SSL certificate
    command: certbot certonly --nginx --non-interactive --agree-tos --email dominik.helfenstein@gmx.de -d api.cs-tracker.com

  - name: Configure NGINX
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-available/default
    notify:
      - Restart NGINX Service

  - name: Enable NGINX default site
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link

  handlers:
  - name: Restart NGINX Service
    service:
      name: nginx
      state: restarted

