---
- name: Install basic packages
  hosts: servers
  become: true
  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes
    - name: Install packages with the latest versions
      apt:
        package:
          - chromium
        state: latest
    - name: Ensure $HOME/flutter/bin is in PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="$HOME/flutter/bin:$PATH"'
        create: true
    - name: Ensure chromium is in PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export CHROME_EXECUTABLE=chromium'
        create: true

