---
- name: Configure Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: csgotracker
        groups: docker
        append: yes

    - name: Enable docker service on system startup
      systemd: 
        name: docker
        enabled: yes

    - name: Add user to docker group (to use docker as non-root)
      user: 
        name: your_username 
        append: yes 
        groups: docker

    - name: Restart Docker to apply changes
      systemd:
        state: restarted
        name: docker

